version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: gazonegazelle17/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/app/media
      - static:/app/static
  frontend:
    image: gazonegazelle17/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: gazonegazelle17/gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/app/media
